In [2]:
import pandas as pd

df = pd.read_csv('../data/retail_store_inventory.csv')
df['Date'] = pd.to_datetime(df['Date'])

In [3]:
df = df.sort_values(by= 'Date')

In [5]:
df['Year '] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Weekday'] = df['Date'].dt.weekday

In [6]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,Year,Month,Day,Weekday
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1,5
72,2022-01-01,S004,P0013,Furniture,East,191,56,65,54.47,61.81,0,Sunny,0,63.92,Autumn,2022,1,1,5
71,2022-01-01,S004,P0012,Electronics,North,349,9,165,0.95,14.25,5,Rainy,1,18.56,Spring,2022,1,1,5
70,2022-01-01,S004,P0011,Electronics,West,205,46,27,46.65,54.84,0,Sunny,1,57.76,Spring,2022,1,1,5
69,2022-01-01,S004,P0010,Groceries,East,447,104,96,115.03,33.48,15,Cloudy,0,37.15,Summer,2022,1,1,5

In [7]:
# creating Lag features

df['sales_lag_1'] = df['Units Sold'].shift(1)
df['sales_lag_7'] = df['Units Sold'].shift(7)

In [8]:
df['rolling_mean_7'] = (
    df['Units Sold']
    .rolling(window=7)
    .mean()
)

In [9]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
Year                  0
Month                 0
Day                   0
Weekday               0
sales_lag_1           1
sales_lag_7           7
rolling_mean_7        6
dtype: int64

In [13]:
df = df.dropna()

In [14]:
df.shape

(73093, 22)

In [15]:
df.dtypes

Date                  datetime64[us]
Store ID                         str
Product ID                       str
Category                         str
Region                           str
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Demand Forecast              float64
Price                        float64
Discount                       int64
Weather Condition                str
Holiday/Promotion              int64
Competitor Pricing           float64
Seasonality                      str
Year                           int32
Month                          int32
Day                            int32
Weekday                        int32
sales_lag_1                  float64
sales_lag_7                  float64
rolling_mean_7               float64
dtype: object

In [16]:
df = pd.get_dummies(
    df,
    columns=[
        "Store ID",
        "Product ID",
        "Category",
        "Region",
        "Weather Condition",
        "Seasonality"
    ],
    drop_first=True
)

In [17]:
df.shape

(73093, 52)

In [18]:
df.head()

,Date,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Holiday/Promotion,Competitor Pricing,Year,...,Category_Toys,Region_North,Region_South,Region_West,Weather Condition_Rainy,Weather Condition_Snowy,Weather Condition_Sunny,Seasonality_Spring,Seasonality_Summer,Seasonality_Winter
66,2022-01-01,264,190,139,197.45,67.26,20,0,64.78,2022,...,False,False,False,True,False,False,False,False,True,False
65,2022-01-01,470,382,195,396.40,41.35,10,0,39.86,2022,...,False,False,False,False,False,True,False,False,True,False
64,2022-01-01,397,200,172,196.57,81.72,0,1,85.22,2022,...,False,True,False,False,False,True,False,True,False,False
63,2022-01-01,437,0,160,-2.40,87.23,10,0,90.36,2022,...,False,False,False,True,False,False,True,True,False,False
62,2022-01-01,446,344,27,352.93,89.32,20,0,93.00,2022,...,False,False,False,True,False,False,False,False,False,False